# Site Settings
title: Simon Kim
description: "Personal website"
url: 'https://simonsk.github.io'
baseurl: '' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Simon Kim
tagline: "Cybersecurity Researcher\nSystem Administrator"
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
about: "I am a cybersecurity researcher at the National Renewable Energy Laboratory (<a href=\"https://www.nrel.gov\" target=\"_blank\">NREL</a>).
        At NREL, I have been primarily contributing to development of the <a href=\"https://www.nrel.gov/security-resilience/cyber-range.html\" target=\"_blank\">ARIES Cyber Range</a>.
        I studied computer science at the University of Illinois at Urbana-Champaign under the guidance of Professor <a href=\"https://faculty.cc.gatech.edu/~mbailey/\" target=\"_blank\">Michael Bailey</a>.
        My interests are large-scale network measurement and IT operations & automation."

#sidebar links
building: Energy Systems Integration Facility
building-map: https://goo.gl/maps/NggbKjc2THW278Rp7
email: simonsk at outlook dot com
#phone: 012 345 6789
#website: blog.webjeda.com #do not add http://
linkedin: simon-sk-kim
github: SimonSK
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
education_in_main: True
experience: True
projects: True
publications: True
skills: True

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
